name: Build modpack

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download and extract packwiz
        run: |
          wget --output-document=packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip ./packwiz.zip -d /usr/local/bin
      
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Build modpack
        run: |
          packwiz refresh --build
          packwiz mr export
      
      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: ./Softimized-*.mrpack

      - name: Add to release
        if: ${{ github.event_name == 'release' }}
        run: gh release upload ${{ github.ref_name }} ./Softimized-*.mrpack

      
      
